### ISSUE TITLE
Regarding Reset Commit

### ISSUE THREAD

**Issue by JihooKang-KOR** [AndreWeiner/wall_modeling#2]
Dear Dr. Weiner,

From this week, a new test case without wall functions should be investigated. Therefore, I changed the folder name of the original test case that uses wall functions in order to distinguish each other, and subsequently I did a commit for it. However, all the related histories in this folder was vanished in Github. That is why I reset this commit, but I would like to ask questions as follows.

1. Could you inform me if I can reset commit in this repository when I did any mistakes? I can revert it as well, but in this case (folder name change), we cannot revive all previous histories in Github.

2. I could check that this commit history was deleted from all the other location except the reference tab in the issue (Getting started #1). I would like to know if this can be deleted in this reference tab as well. The SHA of the reset commits are 50d411f and 0008761 in the tab.

Thank you very much for your help.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,
regarding 2) I think it's not possible to delete the references to commits in an issue; however, don't worry about it.
regarding 1) resetting commits is not the usual way to go; in the future, it would be better to
- create a new branch for a new task
- work on the branch
  - if what you planned initially did not work out, go back to the main branch and delete the working branch
  - if you completed the work successfully, you merge the working branch back into the main branch
  
Let me know if these points answer your questions.
Best, Andre

**Comment by JihooKang-KOR** [comment]
Dear Dr. Weiner,

Thank you for your answer, and I understood your points.

Actually, I always use a branch for any new task until my planned code works. However, I sometimes find small errors after I pushed to Github or some consequences that cannot be discovered in the local git system. Changing file names or folder names is one of the examples. In a local repository, there is no loss of information, whereas the history information of name changed files disappears in Github. Therefore, I would like to follow the rules from now on as given below.
1. Even if there are some very small errors/glitches or some typos, I will make a new commit to revise them. (No reset)
2. If I have to change any file or folder name, I will ask you if it is necessary or not.
3. If some unexpected situations occur in Github after a commit, I will inform you of them before any decision.

If the above rules need to be revised or some of them are not needed, please kindly let me know.
Thank you very much for your help.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,

it is totally fine to commit code that is not perfect and needs to be changed later on. Don't worry about potential mistakes/changes. You simply correct them in later commits. That's a natural part of the development process. No need to change the commit history. The only ever reason you want to fully remove something from the repository is if you committed accidentally very large or sensitive data (huge binary files, passwords, or keys).

As you suggested, if something goes wrong with Git, let me know, and we figure something out. If you consider this issue completed, let me know by closing it ;-)

Best, Andre

**Comment by JihooKang-KOR** [comment]
Dear Dr. Weiner,

Thank you very much for the answer. 
I understood and close this issue now.

Best regards,
Jihoo Kang
