### ISSUE TITLE
Code Interpretation of 'nutUSpaldingWallFunction'

### ISSUE THREAD

**Issue by JihooKang-KOR** [AndreWeiner/wall_modeling#4]
Dear Andre,

With reference to the subject, I made a preliminary version of the LaTeX document for '*nutUSpaldingWallFunction*'.

Here, I mention the link only for viewing the document because I am not sure whether the link for editing also works for all the people who have a overleaf account or any revision is possible only for the allowed people (for the sake of security or safety).

https://www.overleaf.com/read/gckxpqccjrxv

I already sent the sharing request to your e-mail, and therefore you will be able to see and edit the document when you login your overleaf account.

If there is something to revise or change, please kindly let me know about it. In addition, if you would like to delete or not to accept any link for the document, I will make the link sharing off and delete the above link for viewing.

Thank you very much for your help.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,

excellent start! It might be sensible to add some basic definitions at the beginning of the document, e.g.,
- a list of used symbols and their meaning, see [here](https://www.openfoam.com/documentation/guides/latest/doc/guide-bcs-wall-turbulence-nutUSpaldingWallFunction.html)
- basic mathematical definitions like y_plus, u_tau
- a plot showing Spalding's function together with the log-law, as shown [here](https://en.wikipedia.org/wiki/Law_of_the_wall); I suggest using [Pgfplots](https://www.overleaf.com/learn/latex/Pgfplots_package)
- a simple sketch of a representative control volume at the wall to indicate where certain quantities are computed or taken from (e.g., which y is used in the computation? which nu_t is actually set?); I suggest using [Tikz](https://www.overleaf.com/learn/latex/TikZ_package)

Again, really good work, thank you!
Andre

**Comment by JihooKang-KOR** [comment]
Dear Andre,

Thank you for the reviewing the preliminary document.

Currently, I'm working with the above comments, and able to decide how to implement the top 3 comments. However, the last one is not clear for me to implement.
- a simple sketch of a representative control volume at the wall to indicate where certain quantities are computed or taken from (e.g., which y is used in the computation? which nu_t is actually set?); I suggest using Tikz

I guess that a control volume of the turbulent flat plate is like the following link of figure which is from NASA.
https://turbmodels.larc.nasa.gov/FlatPlate/Grids/plateBCpic.jpg

Would you mind informing me if it is a correct concept of a representative control volume? And if so, I would like to know how to indicate the certain quantities and why they should be indicated there. The question is quite obscure because I still don't figure out the last task fully.

Thank you very much for your help.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,

the log-law plot looks great! Two points:
- the definition for tau_w is still missing; this definition is important to make the connection between the velocity normal derivative and the viscosity
- the sketch should roughly look as follows; the symbols are preliminary, so don't worry too much about them
![PXL_20210504_080703344](https://user-images.githubusercontent.com/8482575/116976107-fc359380-acc0-11eb-8ebe-2e3a15fa0799.jpg)

Best, Andre

**Comment by JihooKang-KOR** [comment]
Dear Andre,

I revised and added some contents in the document as per your comment. Please inform me if there is something to be revised or added more. I'm writing here everytime I finished the task of LaTex because I cannot automatically inform any changes for Overleaf unlike Github commits.

I referred to one OpenFOAM wall function document and used google search, but I haven't added a reference section. If this document needs the reference section, I will add it. However, in this case, I need to think about how to cite the reference for each related sentence.

Thank you very much for reviewing the document again.

Warm regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,

the report is already in a very good state. There are some details missing, which will be essential to understand further modifications in the algorithm. I would like you to focus on the following three points next:

1) How is eq. 11 (nut equation) in the current manuscript derived? Some hints for the derivation:
  - What is the actual quantity we can't approximate well in the flow simulation and why?
  - How do we indirectly correct this quantity?
  - Where does our correction come from?
  - Don't worry if you get stuck. I'll give you some more hints if needed, but first, I would like you to go through this thought process yourself ;-)
2) You correctly identified the Spalding equation being used in the Newton iteration, but the explanation is not yet very detailed. Note that we will modify these equations soon, so it is essential to exactly understand where each term comes from. A single wrong sign or term will make the entire algorithm diverge. You already identified some important gotchas like the minus sign in the Newton method being applied to the derivative term. Here are some more things to consider:
  - Have a look at the current definition of u_tau (eq. 6). What are the units if you plug in eq. 4 for tau_w? Why is the density not present in the source code?
  - What is magGradU needed for?
  - What is `turbModel.y()` exactly?
  - Spalding's equation provides you with a function y_plus = f(u_plus); y_plus and u_plus are themselves functions of distance to the wall and velocity, respectively. Where are those functions evaluated?
  - Following the above question, what is the condition used in the Newton iteration?
3) Somewhat independent from the two previous points, where does the reference equation for the wall friction coefficient used to validate the numerical results come from (Weighardt)?

If you have follow-up questions, let me know.

Best, Andre
