### ISSUE TITLE
Implementation of New Wall Function from 'nutUSpaldingWallFunction'

### ISSUE THREAD

**Issue by JihooKang-KOR** [AndreWeiner/wall_modeling#5]
Dear Andre,

I would like to open a new issue regarding the modification of the wall function for '*nut*'. 

I realized that I have to add a template folder of a new wall function if I would like to thoroughly check and test how the C++ code works. Thus, I added the template folder in the repository, and it will be pushed to the Github soon referring this issue. The name of the new wall function is '*nutSGSWallFunction*'. If you would like to change the name, I will delete the files with a commit and make them again with another commit.

I tried as possible as I can, but there was a dependency problem with the following files.
- turbulenceModel.H and -.C
- nutWallFunctionFvPatchScalarField.H and -.C

Therefore, I copied those files to the new wall function folder. Afterward, I found that at least ```wmake libso``` worked well. If you have any other idea to condense the contents in the folder, please kindly let me know.

In addition, I think we can use this issue for implementation of the new wall function. If you also think that this issue can be used for the new wall function, please kindly comment here when you would like to give any instructions for the new wall function later on.

Thank you very much for your help.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,

to sum up our discussion regarding the wall function:
- use `wmake` instead of `wmake libo`; the *Allw** scripts can be removed
- choose a more descriptive name than *nutSGSWallFunction*, e.g, *nutUIntegralSpaldingWallFunction*

Once these small modifications are implemented, this issue can be closed from my point of view.

Best, Andre

**Comment by JihooKang-KOR** [comment]
Dear Andre,

I changed the name of the folder/files and delete the *Allw** scripts in the repository as per your comment.
Therefore, this issue is closed now.

Best regards,
Jihoo Kang
